Repository mishra10008/HacktoberFest2021, pull requests merged in 2021-10, with the labels that each got.

#74 C++
  Linked Lists/BASIC/Check If Circular Linked List - BASIC.c
  Linked Lists/EASY/Absolute List Sorting - EASY.cpp
  Linked Lists/EASY/Add 1 to a number represented as linked list - EASY.cpp
  Linked Lists/EASY/Add two numbers represented by linked lists - EASY.cpp
  Linked Lists/EASY/Arrange Consonants and Vowels - EASY.cpp
  Linked Lists/EASY/Check if Linked List is Palindrome - EASY.cpp
  Linked Lists/EASY/Count Pairs whose sum is equal to X - EASY.cpp
  Linked Lists/EASY/Delete Middle of Linked List - EASY.c
  Linked Lists/EASY/Delete N nodes after M nodes of a linked list - EASY.cpp
  Linked Lists/EASY/Delete without head pointer - EASY.cpp
  Linked Lists/EASY/Detect Loop in linked list - EASY.cpp
  Linked Lists/EASY/Find length of Loop - EASY.cpp
  Linked Lists/EASY/Finding middle element in a linked list - EASY.cpp
  Linked Lists/EASY/Given a linked list of 0s, 1s and 2s, sort it - EASY.cpp
  Linked Lists/EASY/Insert in a Sorted List - EASY.cpp
  Linked Lists/EASY/Intersection of Two Linked Lists - EASY.cpp
  Linked Lists/EASY/Linked List in Zig-Zag fashion - EASY.cpp
  Linked Lists/EASY/Merge 2 sorted linked list in reverse order - EASY.cpp
  Linked Lists/EASY/Multiply two linked lists - EASY.cpp
  Linked Lists/EASY/Nth node from end of linked list - EASY.c
  Linked Lists/EASY/Remove duplicate element from sorted Linked List - EASY.c
  Linked Lists/EASY/Remove duplicates from an unsorted linked list - EASY.cpp
  Linked Lists/EASY/Reverse a Doubly Linked List - EASY.cpp
  Linked Lists/EASY/Reverse a linked list - EASY.c
  Linked Lists/EASY/Segregate even and odd nodes in a Link List - EASY.cpp
  Linked Lists/EASY/Sorted insert for circular linked list - EASY.cpp
  Linked Lists/EASY/Union of Two Linked Lists - EASY.cpp
  Linked Lists/MEDIUM/Delete nodes having greater value on right - MED.cpp
  Linked Lists/MEDIUM/First non-repeating character in a stream - MED.cpp
  Linked Lists/MEDIUM/Intersection Point in Y Shapped Linked Lists - MED.cpp
  Linked Lists/MEDIUM/Leaves to DLL - MED.cpp
  Linked Lists/MEDIUM/Merge two sorted linked lists - MED.cpp
  Linked Lists/MEDIUM/Polynomial Addition - MED.cpp
  Linked Lists/MEDIUM/Rearrange a linked list - MED.cpp
  Linked Lists/MEDIUM/Remove loop in Linked List - MED.cpp
  Linked Lists/MEDIUM/Reverse a Linked List in groups of given size - MED.cpp
  Linked Lists/MEDIUM/Reverse alternate nodes in Link List - MED.cpp
  Linked Lists/MEDIUM/Rotate a Linked List - MED.cpp
  Linked Lists/MEDIUM/Swap Kth nodes from ends - MED.cpp
Labels: good first issue

#76 Added Longest Palindromic Substring Solution
  LeetCode/Longest_Palindromic_Substring.cpp
Labels: good first issue

#102 Added some problems in Greedy.
  Algorithms/Greedy/Indian_coin_change.cpp
  Algorithms/Greedy/activity_selection.cpp
  Algorithms/Greedy/fractional_knapsack.cpp
  Algorithms/Greedy/max_min_diff.cpp
  Algorithms/Greedy/remove_duplicates_from_String.cpp
Labels: good first issue

#111 Chinese remainder theorem added.
  Algorithms/NumberTheory/chinese_remainder.cpp
Labels: good first issue

#110 Added Codeforces 1559C Problem
  Codeforces/C++/1559C.cpp
Labels: good first issue

#107 Add files via upload
  Algorithms/GraphAlgorithms/tsort.cpp
Labels: good first issue

#105 Create Selection sort iterative
  Algorithms/Sorting/Selection sort iterative
Labels: good first issue

#104 Create KMP Algorithm for Pattern Searching.cpp
  Algorithms/PatternSearching/KMP Algorithm for Pattern Searching.cpp
Labels: good first issue

#93 Create stack.py
  DataStructure/4.Stack/stack.py
Labels: good first issue

#98 Sept Lunchtime Solutions Added
  Codechef/SeptemberLunchtime/ALBOFACE.cpp
  Codechef/SeptemberLunchtime/SOD3.cpp
  Codechef/SeptemberLunchtime/TWODISH.cpp
  Codechef/SeptemberLunchtime/UNQEQ.cpp
  Codechef/SeptemberLunchtime/VDATES.cpp
Labels: good first issue

#103 Added 6 Leetcode problems.
  LeetCode/1027. Longest Arithmetic Subsequence.cpp
  LeetCode/1751 Maximum Number of Events That Can Be Attended II.cpp
  LeetCode/2008.Maximum Earnings From Taxi.cpp
  LeetCode/322 Coin Change.cpp
  LeetCode/39 Combination Sum.cpp
  LeetCode/40 Combination Sum II.cpp
Labels: good first issue, leetcode

#92 Create circularQueueUsingArray.cpp
  Linked Lists/BASIC/circularQueueUsingArray.cpp
Labels: good first issue

#108 Create pattern_in_zigzag.cpp
  pattern_in_zigzag.cpp
Labels: good first issue

#99 added 2 code
  LeetCode/1004. Max Consecutive Ones III.cpp
  LeetCode/1358. Number of Substrings Containing All Three Characters.cpp
Labels: good first issue

#94 Added Solutions to 5 tasks of Codeforces Round 744
  Codeforces/C++/1579B.cpp
  Codeforces/C++/1579C.cpp
  Codeforces/C++/1579D.cpp
  Codeforces/C++/1579E1.cpp
  Codeforces/C++/1579E2.cpp
Labels: good first issue, codeforces

#97 Added recursions problems
  Algorithms/Recursions/Factorial.cpp
  Algorithms/Recursions/PrintTheNumberInSequence.cpp
  Algorithms/Recursions/fibonacci.cpp
  Algorithms/Recursions/sumTill_n.cpp
Labels: good first issue

#115 5 problems added under leetcode section
  LeetCode/174. Dungeon Game.cpp
  LeetCode/32. Longest Valid Parentheses.cpp
  LeetCode/91. Decode Ways.cpp
  LeetCode/95. Unique Binary Search Trees II.cpp
  LeetCode/Lets Party !.cpp
Labels: leetcode
